global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configuração de alertas
rule_files:
  - "/etc/prometheus/alerts.yml"

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Jobs de coleta de métricas
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-app"
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
